version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Samsunggalaxyy1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testpostgre
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Samsunggalaxyy1
      - POSTGRES_PORT=5432
      - POSTGRES_DB=testpostgre
    depends_on:
      - postgres